
name: Deploy to EC2 full cicd pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          
          echo "=== Updating EC2 ==="
          sudo apt update -y

          echo "=== Installing Docker ==="
          sudo apt install docker.io -y
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker ubuntu

          echo "=== Installing Git ==="
          sudo apt install git -y

          echo "=== Installing Java (for Spring Boot) ==="
          sudo apt install openjdk-17-jdk -y

          echo "=== Cloning/Pulling Repo ==="
          cd /home/ubuntu/
          if [ ! -d "project" ]; then
            git clone https://github.com/amit6264/Java-springboot-project.git project
          fi

          cd project
          git pull

          echo "=== Building Docker Images ==="
          sudo docker build -t backend:latest ./backend
          sudo docker build -t frontend:latest ./frontend

          echo "=== Stopping Old Containers ==="
          sudo docker stop backend || true
          sudo docker rm backend || true
          sudo docker stop frontend || true
          sudo docker rm frontend || true

          echo "=== Running New Containers ==="
          sudo docker run -d --name backend -p 8084:8084 backend:latest
          sudo docker run -d --name frontend -p 8501:8501 frontend:latest

          echo "=== Deployment Finished Successfully ==="

          EOF
